In [112]:
import numpy as np
from sklearn import svm
import pandas as pd

In [11]:
clf = svm.SVC()

In [103]:
class Dataset:
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.x_train = X
        self.y_train = y
        self.x_test = X
        self.y_test = y        
    
    def split(self, percentage):
        idx = np.arange(len(self.X))
        np.random.shuffle(idx)
        
        sX = self.X[idx]
        sy = self.y[idx]
        
        n_train = int(len(self.X) * percentage)
        self.x_train = sX[:n_train]
        self.y_train = sy[:n_train]
        self.x_test = sX[n_train:]
        self.y_test = sy[n_train:]
    
    def __len__(self):
        return len(self.y)
    
    def __repr__(self):
        cls = self.__class__.__name__
        n = len(self.y)
        num_features = self.X.shape[1]
        return f'{cls}(samples={n}, features={num_features})'

In [ ]:
class Learner:
    def __init__(self, name, model, param):
        self.name = name
        self.model = model
        self.params = param
        self.data = None
    
    def load_data(self, X, y):
        self.data = Dataset(X, y)
    
    def train_model(self):
        if self.data == None:
            print("Dataset has not been set.")
        else:
            self.model.fit(self.data.x_train, self.data.y_train)            
    
    def eval_model(self):
        pass
    
    def __repr__(self):
        cls = self.__class__.__name__
        return f'{cls}(model={self.name!r})'

In [39]:
X = np.array([[0, 0], [1, 1], [1, 0], [0, 1]])
y = np.array([0, 0, 1, 1])

In [70]:
df = pd.read_csv("iris.csv")

In [71]:
# df.species = pd.Categorical(df.species)
df[['classes']] = df[['species']].apply(lambda col:pd.Categorical(col).codes)


In [79]:
X = df.iloc[:, 0:-2].copy().to_numpy()
y = df.iloc[:,-1].copy().to_numpy()

In [104]:
d = Dataset(X, y)

In [105]:
d.split(0.8)

In [106]:
len(d)

150

In [107]:
l = Learner("SVM", clf, [])

In [108]:
l.load_data(X,y)

In [109]:
l.train_model()

In [110]:
l.model.predict(d.x_test)

array([1, 1, 1, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0], dtype=int8)

In [111]:
d.y_test

array([1, 0, 2, 1, 1, 2, 0, 0, 1, 2, 0, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 2, 1, 0, 1, 2], dtype=int8)

In [97]:
idx = np.arange(len(y))
np.random.shuffle(idx)

In [101]:
X[idx]

array([[7.2, 3.2, 6. , 1.8],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 2.4, 3.3, 1. ],
       [5.4, 3.4, 1.7, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [5.7, 2.5, 5. , 2. ],
       [6.5, 3. , 5.8, 2.2],
       [5.4, 3.9, 1.3, 0.4],
       [6.1, 2.6, 5.6, 1.4],
       [6.3, 2.3, 4.4, 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [5.1, 3.8, 1.5, 0.3],
       [6.2, 2.9, 4.3, 1.3],
       [6. , 2.2, 5. , 1.5],
       [4.4, 2.9, 1.4, 0.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 3. , 4.5, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3. , 1.4, 0.2],
       [6.7, 3.3, 5.7, 2.5],
       [4.5, 2.3, 1.3, 0.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.8, 2.7, 5.1, 1.9],
       [5.3, 3.7, 1.5, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.4, 3. , 4.5, 1.5],
       [6.3, 2.5, 4.9, 1.5],
       [7.2, 3. , 5.8, 1.6],
       [4.4, 3.2, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [6. , 2

In [142]:
import learner_module
import pandas as pd

In [143]:
l = learner_module.classification_algorithms

In [146]:
l.keys()

dict_keys(['LR', 'DTC', 'RFC', 'GBC', 'KNN', 'LSVM', 'Q-SVM', 'C-SVM', 'RBF-SVM', 'GNB', 'MNB', 'MLP', 'KMC', 'GMM'])

In [ ]:
for k,v in learner_module.classification_algorithms.items():
    print(v)

In [6]:
df = pd.DataFrame.from_dict(learner_module.classification_algorithms)

In [8]:
df.T

long_name  \
LR                                     Logistic Regression   
DTC                               Decision Tree Classifier   
RFC                               Random Forest Classifier   
GBC                           Gradient Boosting Classifier   
KNN                         K-Nearest Neighbors Classifier   
LSVM                         Linear Support Vector Machine   
Q-SVM                     Quadratic Support Vector Machine   
C-SVM                         Cubic Support Vector Machine   
RBF-SVM       Radial Basis Function Support Vector Machine   
GNB                                   Gaussian Naive Bayes   
MNB                                Multinomial Naive Bayes   
MLP                      Multi-Layer Perceptron Classifier   
KMC      K-Means Clustering (used for classification vi...   
GMM      Gaussian Mixture Model (used for classificatio...   

                                                  function  \
LR       <class 'sklearn.linear_model._logistic.Logisti...   
DTC      <class 'sklearn.tree._classes.DecisionTreeClas...   
RFC      <class 'sklearn.ensemble._forest.RandomForestC...   
GBC      <class 'sklearn.ensemble._gb.GradientBoostingC...   
KNN      <class 'sklearn.neighbors._classification.KNei...   
LSVM                    <class 'sklearn.svm._classes.SVC'>   
Q-SVM                   <class 'sklearn.svm._classes.SVC'>   
C-SVM                   <class 'sklearn.svm._classes.SVC'>   
RBF-SVM                 <class 'sklearn.svm._classes.SVC'>   
GNB               <class 'sklearn.naive_bayes.GaussianNB'>   
MNB            <class 'sklearn.naive_bayes.MultinomialNB'>   
MLP      <class 'sklearn.neural_network._multilayer_per...   
KMC               <class 'sklearn.cluster._kmeans.KMeans'>   
GMM      <class 'sklearn.mixture._gaussian_mixture.Gaus...   

                                                parameters  
LR                          [penalty, C, solver, max_iter]  
DTC      [criterion, max_depth, min_samples_split, min_...  
RFC      [n_estimators, criterion, max_depth, min_sampl...  
GBC      [n_estimators, learning_rate, max_depth, subsa...  
KNN                   [n_neighbors, weights, algorithm, p]  
LSVM                        [kernel='linear', C, max_iter]  
Q-SVM                  [kernel='poly', degree=2, C, gamma]  
C-SVM                  [kernel='poly', degree=3, C, gamma]  
RBF-SVM                           [kernel='rbf', C, gamma]  
GNB                                        [var_smoothing]  
MNB                                     [alpha, fit_prior]  
MLP      [hidden_layer_sizes, activation, solver, learn...  
KMC                   [n_clusters, init, n_init, max_iter]  
GMM      [n_components, covariance_type, init_params, m...